---
- name: check minecraft basedir state
  stat:
    path: /opt/minecraft
  register: p

- include_role:
    name: backup
    tasks_from: restore_restic.yml
  vars:
    backup_restic:
      env: "{{ backup_dirs[backup].dest[minecraft_restore_src] }}"
  with_items: "{{ minecraft_restore_elements }}"
  loop_control:
    loop_var: backup
  when: not p.stat.exists
