---

- name: prepare the restic configs for the cron jobs
  set_fact:
    restic_repos_mc: "{{ lookup('template', 'restic-cron-jobs.yml.j2',template_vars=dict(dests=backup_dests,parts=backup_parts)) | from_yaml  }}"

- name: Template a file to /etc/files.conf
  become: true
  template:
    src: minecraft_backup_script.sh.j2
    dest: /usr/local/bin/minecraft_restic_backup
    owner: root
    group: root
    mode: '+x'

# configure restic backups
- include_role:
    name: paulfantom.restic
  vars:
    restic_repos: "{{ restic_repos_mc }}"
