---

- name: execute a archive base backup
  block:
    - name: "no post tasks by default"
      set_fact:
        publishing_task: "empty.yml"

    - name: using fetch the backup as post task
      set_fact:
        publishing_task: "fetching_backup.yml"
      when: backup_adhoc_publish == "local"

    - include_role:
        name: backup
        tasks_from: adhoc_backup.yml
      vars:
        backup_adhoc_hook: "archive_content.yml"
        backup_adhoc_post_hook: "{{ publishing_task }}"

  when: backup_type == "archive"

- name: execute Restic Backups
  block:
    - debug: msg="restic"

    - include_role:
        name: backup
        tasks_from: adhoc_restic dests.yml
      with_items: "{{ backup_dests }}"
      loop_control:
        loop_var: current_dest

  when: backup_type == "restic"
