---
- name: restore restic backup
  shell: "{{ restic_command }} restore latest --target /"
  environment:
    RESTIC_REPOSITORY: "{{ backup.repo.RESTIC_REPOSITORY }}"
    RESTIC_PASSWORD: "{{ backup.repo.RESTIC_PASSWORD }}"
  become_user: root
  become: true
  tags:
  - skip_ansible_lint
