---
dependency:
  name: galaxy
  options:
    role-file: ./requirements.yml
driver:
  name: vagrant
  provider:
    name: parallels
lint:
  name: yamllint
  enabled: false
platforms:
  - name: instance-1
    box: centos/7
    memory: 4096
    cpus: 2
    groups:
      - minecraftgameserver
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        local_inventory_path: "{{ playbook_dir }}/../inventories"
        sshd_AllowUsers: 
          - vagrant
          - "{{ ansible_user }}"        
      minecraftgameserver:        
        plugin_config_dir: "{{ local_inventory_path }}/pluginconfigs"
        pluginset: "server"
        mc_accept_eula: ${mc_accept_eula}
        mc_version: 1.14.3
        pluginset: "server"
        restic_repos_localbackup_url: /tmp/localbackup
        restic_active: true
        mc_plugins_file: "{{ local_inventory_path }}/pluginlist.yml"
        mc_rcon_password: "password"

  playbooks:
    converge: ../../master_playbook-mc-server.yml
  lint:
    name: ansible-lint
    enabled: false
    options:
      x:
        - ANSIBLE0006
        - ANSIBLE0010
        - ANSIBLE0011
        - ANSIBLE0016
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy  
verifier:
  name: testinfra
  directory: ../../../maintenance-test
  lint:
    name: flake8
    enabled: false
