---
- hosts: minecraftgameserver
  vars:
    backup_dest: "s3"
  vars_files:
    - ./../vars/facts_mc_node.yml
  tasks:


    - include_role:
        name: backup

#    - include_role:
#        name: backup
#        tasks_from: adhoc_backup.yml
#      vars:
#        backup_adhoc_hook: "archive_content.yml"
#        backup_adhoc_post_hook: "empty.yml"

#    - include_role:
#        name: backup
#        tasks_from: adhoc_backup.yml
#      vars:
#        gdrive_parent_folder_id: "{{ backup_gdrive_parent_folder_id }}"
#        backup_adhoc_hook: "archive_content.yml"
#        #backup_adhoc_hook: "empty.yml"
#        #archive_dest: "/tmp/backup-20190707T201746.tar.gz"
#        backup_adhoc_post_hook: "publish_gdrive.yml"

#    - include_role:
#        name: backup
#        tasks_from: adhoc_backup.yml
#      vars:
#        backup_adhoc_hook: "adhoc_restic.yml"
#        backup_restic:
#          source:
#            basedir: /opt/minecraft/plugins
#            excludes:
#              - shared/dynmap/*
#          env:
#            RESTIC_S3_URL: https://static.119.158.216.95.clients.your-server.de
#            RESTIC_S3_BUCKET: backup
#            RESTIC_S3_PATH: "/mctestserver/restic/plugindata"
#
#            RESTIC_PASSWORD: dolphins
#            AWS_ACCESS_KEY_ID: "{{ s3_access_key }}"
#            AWS_SECRET_ACCESS_KEY: "{{ s3_secret_key }}"

#    - include_role:
#        name: backup
#        tasks_from: adhoc_backup.yml
#      vars:
#        backup_restic:
#          source:
#            basedir: "{{ current_backup_dir.source.basedir }}"
#            excludes: "{{ current_backup_dir.source.excludes | default([]) }}"
#          env: "{{ current_backup_dir.dest[backup_dest] }}"
#        backup_adhoc_hook: "adhoc_restic.yml"
#      with_items: "{{ backup_dirs }}"
#      loop_control:
#        loop_var: current_backup_dir



#
#    - include_role:
#        name: backup
#        tasks_from: adhoc_backup.yml
#      vars:
#        backup_restic:
#          source:
#            basedir: "{{ current_backup_dir.source.basedir }}"
#            excludes: "{{ current_backup_dir.source.excludes | default([]) }}"
#          env: "{{ current_backup_dir.repo }}"
#        backup_adhoc_hook: "adhoc_restic.yml"
#      with_items: "{{ backup_dirs }}"
#      loop_control:
#        loop_var: current_backup_dir
