---
- src: git+https://github.com/nolte/ansible-minecraft
  name: nolte.minecraft
  version: develop
- name: ypsman.sshd_config
#- name: mrlesmithjr.ipset
- name: dev-sec.os-hardening
- name: robertdebock.fail2ban
- name: geerlingguy.java
#- name: robertdebock.bootstrap
#- name: robertdebock.epel
- name: donat-b.restic
