Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  config.vm.network "forwarded_port", guest: 25565, host: 25567
  config.vm.network "forwarded_port", guest: 25564, host: 25566
  config.vm.network "forwarded_port", guest: 8123, host: 8123
  config.vm.network "forwarded_port", guest: 433, host: 433
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision "shell", inline: "yum -y install git unzip python-netaddr"

  config.vm.box = "centos/7"

  config.vm.provision "ansible_local" do |ansible|
#    ansible.verbose = "vvv"
    ansible.become = true
    ansible.galaxy_role_file = 'maintenance/requirements.yml'
    ansible.inventory_path = "inventories/test"
    ansible.limit = "minecraftgameserver"
    ansible.extra_vars = {
      user_accept_minecraft_eula: ENV['mc_accept_eula']
    }
    ansible.playbook = "maintenance/masterplaybook-mc-server.yml"
  end
end
