@startuml
cloud hetzner {

node node as "Game Server"

note right of [node]
  ECS Instance with 20GB
  internal storage
end note

storage hotstorage as "<b>HotStorage</b> \n Backup"

note right of [hotstorage]
  Mounted <b>20GB</b> Volume
  for restic repository
  ~$0.048/GB/Month
end note

node <--> hotstorage

}
cloud backblaze as "backblaze.com" {

storage coldstorage as "<b>Cold Storage</b> \n Backup"

note right of [coldstorage]
  cheap storage for long time
  backups ~$0.005/GB/Month
end note

}
@enduml
