---
on:
  push:

jobs:
  static:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-pre-commit.yaml@v1.1.10
  security:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-trivy.yaml@v1.1.10
